### ISSUE TITLE
Getting issue while building it on aarch64 platform

### ISSUE THREAD

**Issue by odidev** [dukescript/maven-archetypes#1]
While building it on aarch64 platform, getting following issue:
`java.lang.UnsatisfiedLinkError: /home/travis/.openjfx/cache/11/libprism_es2.so: /home/travis/.openjfx/cache/11/libprism_es2.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)`

U can see the whole logs at:
https://travis-ci.com/github/Ross1503/maven-archetypes/jobs/302522849

Looks like it is downloading "libprism_es2.so" & "libprism_sw.so" files for amd64 platform even if we are running it on aarch64 platform. It is working fine if we manually copy those two files(which are of aarch64 platform) from "/usr/lib/aarch64-linux-gnu/jni/" to desired location.
Do we need to download anything specific for aarch64 platform.
Also would you be interested in adding arm64 jobs in travis.yml, just to make sure that it is working fine on both platforms(amd64 & arm64).

**Comment by dukescript** [comment]
Thanks for trying the archetypes on AARCH64 platform! Out of curiosity: What's your overall intent?

> Looks like it is downloading "libprism_es2.so" & "libprism_sw.so" files for amd64 platform even if we are running it on aarch64 platform. 

The archetypes add a [Maven dependency on OpenJFX artifacts](https://github.com/dukescript/maven-archetypes/blob/master/ko-archetype/src/main/resources/archetype-resources/client/pom.xml#L231). There seem to be only [amd64 versions for linux, win and mac](https://repo1.maven.org/maven2/org/openjfx/javafx-web/15-ea+2/) out there. The selected Linux version is AMD64 and it obviously clashes with your architecture.

> It is working fine if we manually copy those two files(which are of aarch64 platform) from "/usr/lib/aarch64-linux-gnu/jni/" to desired location.

Where do you get an OpenJFX version for AARCH64? Is it available on Maven central? It would be ideal if support for AARCH64 was added directly into [OpenJFX artifacts](https://search.maven.org/artifact/org.openjfx/javafx-web/15-ea%2B2/jar).

> Do we need to download anything specific for aarch64 platform.

Try to remove the [dependency on OpenJFX artifacts](https://github.com/dukescript/maven-archetypes/blob/master/ko-archetype/src/main/resources/archetype-resources/client/pom.xml#L231) to begin with. That will remove the clash with wrong AMD64 bits.

> Also would you be interested in adding arm64 jobs in travis.yml, 
> just to make sure that it is working fine on both platforms(amd64 & arm64).

That would be great! Feel free to get it working somehow. Suggest integration of your changes via a PR. Together we'll get it working! The major concern to overcome may be: Where to get a JDK with JavaFX support for ARM64?

**Comment by odidev** [comment]
Hi @dukescript, 
Above issue is getting resolved by installing another dependency named "**libopenjfx-jni**". after installing it by "**apt-get install libopenjfx-jni**" it is running successfully on **aarch64** plateform as well. and we are getting similar results as of AMD64.
Can we add this info in README or on GitHub page so that it helps people in future.
Thanks.

**Comment by dukescript** [comment]
Glad to hear the issue is solved. Sure, please feel free to update the `README.md` in a pull request.  We'll accept it ASAP.

Possibly consider updating [Apache HTML/Java API](https://github.com/apache/netbeans-html4j/blob/master/boot-fx/src/main/java/org/netbeans/html/boot/fx/AbstractFXPresenter.java) to detect the problem and adequate advice when the initialization fails.
